services:
  front.ps.net:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    image: unite-psi
    # pull_policy: always
    container_name: ps.front
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      API_KEY: ${UPSI_API_KEY}
      ADMIN_USER: ${UPSI_ADMIN_USER}
      ADMIN_PASSWORD: ${UPSI_ADMIN_PASSWORD}
      AUTHORIZED_USERS: ${UPSI_AUTHORIZED_USERS}
      LDAP_SERVER: ${LDAP_SERVER}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_SERVICE_USER_RNA: ${LDAP_SERVICE_USER_RNA}
      LDAP_SERVICE_USER_PASSWORD: ${LDAP_SERVICE_USER_PASSWORD}
      LDAP_USER_TARGET_OU: ${LDAP_USER_TARGET_OU}
      ML_BASE_URL: "http://back.ps.net:8080"
      ML_API_KEY: ${ML_API_KEY}
      ML_API_VERSION: 3.1
      no_proxy: back.ps.net
    # volumes:
    #   - "./ssl:/https:ro"
    ports:
      # - "80:80"
      # - "443:443"
      - "42100:80"
    depends_on:
      - back.ps.net

  back.ps.net:
    image: medicalinformatics/mainzelliste:1.10-latest
    container_name: ps.back
    restart: unless-stopped
    environment:
      ML_ALLOWEDREMOTEADDRESSES: 0.0.0.0/0
      ML_LOG_LEVEL: info
      MANDATORY_VARIABLES: "ML_DB_PASS ML_API_KEY"
      ML_API_KEY: ${ML_API_KEY}
      # ML_DB_TYPE: postgresql
      # ML_DB_DRIVER: org.postgresql.Driver
      ML_DB_HOST: data.ps.net
      ML_DB_PORT: 5432
      ML_DB_NAME: ${ML_DB_NAME}
      ML_DB_USER: ${ML_DB_USER}
      ML_DB_PASS: ${ML_DB_PASS}
    secrets:
      - mainzelliste.docker.conf
    volumes:
      - ps.back:/usr/local/tomcat/logs/
    ports:
      - "42101:8080"
    depends_on:
      - data.ps.net

  data.ps.net:
    image: postgres:15-alpine
    container_name: ps.data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${ML_DB_NAME}
      - POSTGRES_USER=${ML_DB_USER}
      - POSTGRES_PASSWORD=${ML_DB_PASS}
    volumes:
      - ps.data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

secrets:
  mainzelliste.docker.conf:
    file: ./mainzelliste.docker.conf

volumes:
  ps.data:
    name: ps.data
    driver: local
  ps.back:
    name: ps.back
    driver: local

networks: 
  default:
    name: ps
    external: true