services:
  upsi:
    platform: linux/amd64
    build:
      context: ./src
    image: upsi
    container_name: upsi
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/upsi-cert.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/upsi-key.pem
      JWT_KEY: ${JWT_KEY}
      LDAP_SERVER: ${LDAP_SERVER}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_SERVICE_USER_RNA: ${LDAP_SERVICE_USER_RNA}
      LDAP_SERVICE_USER_PASSWORD: ${LDAP_SERVICE_USER_PASSWORD}
      LDAP_USER_TARGET_OU: ${LDAP_USER_TARGET_OU}
      LDAP_AUTHORIZED_USER_IDS: ${LDAP_AUTHORIZED_USER_IDS}
      MAINZELLISTE_BASE_URL: ${MAINZELLISTE_BASE_URL}
      MAINZELLISTE_API_KEY: ${MAINZELLISTE_API_KEY}
      MAINZELLISTE_API_VERSION: 3.2
    volumes:
      - "./ssl:/https:ro"
