services:
  data.ps.net:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: ps.data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${ML_DB_NAME}
      - POSTGRES_USER=${ML_DB_USER}
      - POSTGRES_PASSWORD=${ML_DB_PASS}
    volumes:
      - ps.data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  ps.data:
    name: ps.data
    driver: local

networks: 
  default:
    name: ps
    external: true