version: '3.1'
services:
  upsi:
    image: upsi
    container_name: upsi
    restart: unless-stopped
    environment:
      # ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_ENVIRONMENT: Development
      # ASPNETCORE_HTTPS_PORT: 443
      # ASPNETCORE_URLS: https://+:443;http://+:80
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /https/upsi-cert.pem
      # ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/upsi-key.pem
      JWT_KEY: ""
      LDAP_SERVER: ""
      LDAP_PORT: ""
      LDAP_SERVICE_USER_RNA: ""
      LDAP_SERVICE_USER_PASSWORD: ""
      LDAP_USER_TARGET_OU: ""
      LDAP_AUTHORIZED_USER_IDS: "a123b,c456d"
      MAINZELLISTE_BASE_URL: ""
      MAINZELLISTE_API_KEY: ""
      MAINZELLISTE_API_VERSION: 3.2
    # volumes:
    #   - "./ssl:/https:ro"
    # ports:
    #   - "80:80"
    #   - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.upsi.rule=Host(`dkfzpsndev.inet.dkfz-heidelberg.de`)" # && PathPrefix(`/upsi`)"
      # - "traefik.http.middlewares.upsi-strip.stripprefix.prefixes=/upsi"
      # - "traefik.http.routers.upsi.middlewares=upsi-strip"
    networks:
      - traefik
      - default